apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume
  namespace: audit-db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
