apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-volume
  namespace: 3scale-logs
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
