CREATE TABLE `audits-3scale` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `id_audit` bigint(20) DEFAULT NULL,
  `auditable_id` bigint(20) DEFAULT NULL,
  `auditable_type` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL,
  `user_type` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `username` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `action` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `version` int(11) DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `tenant_id` bigint(20) DEFAULT NULL,
  `provider_id` bigint(20) DEFAULT NULL,
  `kind` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `audited_changes` text COLLATE utf8_bin,
  `comment` text COLLATE utf8_bin,
  `associated_id` int(11) DEFAULT NULL,
  `associated_type` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `remote_address` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `request_uuid` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `index_audits_on_action` (`action`) USING BTREE,
  KEY `index_audits_on_auditable_id_and_auditable_type_and_version` (`auditable_id`,`auditable_type`,`version`) USING BTREE,
  KEY `index_audits_on_created_at` (`created_at`) USING BTREE,
  KEY `index_audits_on_kind` (`kind`) USING BTREE,
  KEY `index_audits_on_provider_id` (`provider_id`) USING BTREE,
  KEY `index_audits_on_request_uuid` (`request_uuid`) USING BTREE,
  KEY `user_index` (`user_id`,`user_type`) USING BTREE,
  KEY `index_audits_on_version` (`version`) USING BTREE,
  KEY `associated_index` (`associated_type`,`associated_id`),
  KEY `auditable_index` (`auditable_type`,`auditable_id`,`version`)
) ENGINE=InnoDB AUTO_INCREMENT=438792 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;